// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgEH3Vrdotd4kI6OQmwyFWGUo9LgIFFQM',
    appId: '1:289193343354:web:16100fdc55d3dfad2bfec3',
    messagingSenderId: '289193343354',
    projectId: 'mindtrack-fb6c5',
    authDomain: 'mindtrack-fb6c5.firebaseapp.com',
    storageBucket: 'mindtrack-fb6c5.firebasestorage.app',
    measurementId: 'G-6PFDLMZ7KK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe6CpTJb3mjMZJApYb0ZB3Dqpq05fM7Vg',
    appId: '1:289193343354:android:7060854174b7b5932bfec3',
    messagingSenderId: '289193343354',
    projectId: 'mindtrack-fb6c5',
    storageBucket: 'mindtrack-fb6c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg_7BoV7whU0v4xhRotD4VHa4vV8-IzyM',
    appId: '1:289193343354:ios:a5ca7e87dc3e1ba22bfec3',
    messagingSenderId: '289193343354',
    projectId: 'mindtrack-fb6c5',
    storageBucket: 'mindtrack-fb6c5.firebasestorage.app',
    iosClientId: '289193343354-da4vu500oeibc30oq4tuu44o4ek68hfo.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindtrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg_7BoV7whU0v4xhRotD4VHa4vV8-IzyM',
    appId: '1:289193343354:ios:a5ca7e87dc3e1ba22bfec3',
    messagingSenderId: '289193343354',
    projectId: 'mindtrack-fb6c5',
    storageBucket: 'mindtrack-fb6c5.firebasestorage.app',
    iosClientId: '289193343354-da4vu500oeibc30oq4tuu44o4ek68hfo.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindtrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgEH3Vrdotd4kI6OQmwyFWGUo9LgIFFQM',
    appId: '1:289193343354:web:bc600d8a5da3bd012bfec3',
    messagingSenderId: '289193343354',
    projectId: 'mindtrack-fb6c5',
    authDomain: 'mindtrack-fb6c5.firebaseapp.com',
    storageBucket: 'mindtrack-fb6c5.firebasestorage.app',
    measurementId: 'G-LYG2JSN2D8',
  );
}
